### ISSUE TITLE
Viz Container stops overnight

### ISSUE THREAD

**Issue by AAndersn** [GRIDAPPSD/gridappsd-viz#466]

**Comment by AAndersn** [comment]
GridAPPSD Viz container is stopping by itself overnight.

Error message in logs:

```

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.14.15
3 info using node@v14.17.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle gridappsd-viz-server@1.0.0~prestart: gridappsd-viz-server@1.0.0
6 info lifecycle gridappsd-viz-server@1.0.0~start: gridappsd-viz-server@1.0.0
7 verbose lifecycle gridappsd-viz-server@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle gridappsd-viz-server@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/gridappsd/viz/server/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle gridappsd-viz-server@1.0.0~start: CWD: /gridappsd/viz/server
10 silly lifecycle gridappsd-viz-server@1.0.0~start: Args: [ '-c', 'node dist/src/index.js' ]
11 silly lifecycle gridappsd-viz-server@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle gridappsd-viz-server@1.0.0~start: Failed to exec start script
13 verbose stack Error: gridappsd-viz-server@1.0.0 start: `node dist/src/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid gridappsd-viz-server@1.0.0
15 verbose cwd /gridappsd/viz/server
16 verbose Linux 5.15.0-60-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v14.17.6
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error gridappsd-viz-server@1.0.0 start: `node dist/src/index.js`
22 error Exit status 1
23 error Failed at the gridappsd-viz-server@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ShuhaoBai** [comment]
I've pushed my fix to https://github.com/GRIDAPPSD/gridappsd-viz/tree/fix/docker-stop-overnight but I'm not sure how to test it on the virtual machine. Could you please help to let me know how can I test it? @AAndersn Thank you!

**Comment by ShuhaoBai** [comment]
Sent an email to Tonya to rebuild the container and let it run a day or two to see if this fix worked.

**Comment by AAndersn** [comment]
New error message. 

```

> gridappsd-viz-server@1.0.0 start /gridappsd/viz/server
> node dist/src/index.js

Server started on port 8082
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gridappsd-viz-server@1.0.0 start: `node dist/src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gridappsd-viz-server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by AAndersn** [comment]
Moving into backlog for current quarter. This is only happening on a specific pair of servers
